services:
  - type: web              # MCP gateway
    name: mcp-gateway
    runtime: node          # ← required for a Node.js service
    plan: starter
    envVars:               # ← (not “env:”)
      - key: SUPABASE_SSE_URL
        fromSecret: SUPABASE_SSE_URL
    buildCommand: npm install
    startCommand: npm start

  - type: worker           # AI agent fleet
    name: ai-agent-worker
    runtime: node          # ← required here too
    plan: starter
    envVars:
      - key: GATEWAY_URL
        value: https://mcp-gateway.onrender.com/streams
    buildCommand: npm install
    startCommand: npm start
    numInstances: 25
    autoDeploy: true
