services:
  - type: web            # MCP gateway, only Supabase for now
    name: mcp-gateway
    runtime: node
    plan: starter
    envVars:
      - key: SUPABASE_SSE_URL
        sync: false            # ← prompt you for this secret in the Dashboard
    buildCommand: npm install
    startCommand: npm start

  - type: worker         # your agent fleet
    name: ai-agent-worker
    runtime: node
    plan: starter
    envVars:
      - key: GATEWAY_URL
        value: https://mcp-gateway.onrender.com/streams
    buildCommand: npm install
    startCommand: npm start
    numInstances: 25
    autoDeploy: true
