services:
  - type: web            # MCP gateway, only Supabase for now
    name: mcp-gateway
    plan: starter
    env:
      - key: SUPABASE_SSE_URL      # the ENV VAR your code reads
        fromSecret: SUPABASE_SSE_URL  # the name of the secret in Render
    buildCommand: npm install
    startCommand: npm start

  - type: worker         # your agent fleet
    name: ai-agent-worker
    plan: starter
    env:
      - key: GATEWAY_URL
        value: https://mcp-gateway.onrender.com/streams
    buildCommand: npm install
    startCommand: npm start
    numInstances: 25
    autoDeploy: true
